spring:
  application:
    name: beancontainer
  datasource:
    url: jdbc:mysql://beancontainer-db.c1i8occuqpud.ap-northeast-2.rds.amazonaws.com:3306/beancontainer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.naver.com
    port: 465
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 500000
        smtp.starttls.enable: true
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${OAUTH_NAVER_ID} #서비스에서 발급 받은 아이디
            client-secret: ${OAUTH_NAVER_SECRET}  #서비스에서 발급 받은 비밀번호
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
          kakao:
            client-id: ${OAUTH_KAKAO_ID} #서비스에서 발급 받은 아이디
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100



jwt:
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}


default:
  profile:
    image: BeanContainer.png


cloud:
  aws:
    credentials:
      instance-profile: false
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}


